### ISSUE TITLE
Archive if not used anymore

### ISSUE THREAD

**Issue by pllim** [astropy/astropy-docker#6]
If this repo is no longer being used, we should archive it.

**Comment by pllim** [comment]
Maybe we can archive if astropy/astropy#12032 is accepted.

**Comment by bsipocz** [comment]
Are the 32bit images not used anywhere any more? We should be sure that's true for affiliated packages, too.

Otherwise :+1: for archiving, after all we can always unarchive if we start building dockers again

**Comment by astrofrog** [comment]
I think this is safe to archive, and easy to unarchive if anyone does end up needing some of the images (though our 32-bit images are not as good as the one we use in astropy core now)
